name: Flutter Build and Upload Android APK

on:
  push:                 
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: microsoft

      #  Decode keystore File from repository secrets
      #  Keep the keystore file private; don't check it into public source control!
      
      #- name: Decode KeyStore File (.jks)            
      #  run: echo "${{ secrets.KEYSTORE_JKS_PROD }}" | base64 --decode > android/keystore.jks

      #- name: Decode android/key.properties
      #  run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

      - name: Install yq
        uses: mikefarah/yq@v4.42.1

      - name: Get pubspec version
        id: get_flutter_app_version
        run: |
          VERSION=$(yq eval '.version' pubspec.yaml)
          echo "Current version from pubspec.yaml: $VERSION"
          echo "TAG_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if [ $(git tag -l "v${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}") ]; then
            echo "Tag exists, incrementing build number"
            BUILD_NUMBER=$(date +%s)
            echo "FINAL_TAG=${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}+$BUILD_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "FINAL_TAG=${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'main'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Build an AppBundle
        run: flutter build appbundle --release

      - name: Save APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-appbundle
          path: build/app/outputs/bundle/release/*.aab

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab,build/app/outputs/flutter-apk/*.apk"
          tag: "v${{ steps.check_tag.outputs.FINAL_TAG }}"
          allowUpdates: true
          makeLatest: true

  # TODO:  Upload to Firebase - for App Distribution
  # Release job, upload the apk or aab to Firebase App Distribution
  # release:
  #   name: Sends Release APK to Firebase
  #   needs: [ build ]
  #   runs-on: ubuntu-latest
  #   steps:
    
  #   # Retrieve apk file from GitHub artifacts
  #   - uses: actions/checkout@v3
  #   - name: Get flutter-apk from artifacts
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: flutter-apk
  #  OR
  #       name: flutter-appbundle

  #   # Upload apk file to Firebase
  #   - name: Upload artifact to Firebase App Distribution
  #     uses: wzieba/Firebase-Distribution-Github-Action@v1
  #     with:
  #       appId: ${{secrets.FIREBASE_IOS_APP_ID}}
  #       serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
  #       groups: android-developers
  #       file: ${{secrets.APP_NAME}}.apk
  #  OR
  #       file: ${{secrets.APP_NAME}}.aab
